# XXX: change the labels within the following appropriately
import label.anon_funcs
import label.auto_res_markers
import label.booleans
import label.characters
import label.comments
import label.deref_forms
import label.discard_exprs
import label.eval_forms
import label.keywords
import label.lists
import label.maps
import label.metadata
import label.namespaced_maps
import label.nils
import label.numbers
import label.old_metadata
import label.quote_forms
import label.read_cond_splicings
import label.read_conds
import label.regex
import label.sets
import label.strings
import label.symbolic_values
import label.symbols
import label.syntax_quote_forms
import label.tagged_literals
import label.unquote_forms
import label.unquote_splicing_forms
import label.var_quote_forms
import label.vectors
import label.whitespace
