# XXX: change the labels within the following appropriately
import custom.label.anon_funcs
import custom.label.auto_res_markers
import custom.label.booleans
import custom.label.characters
import custom.label.comments
import custom.label.deref_forms
import custom.label.discard_exprs
import custom.label.eval_forms
import custom.label.keywords
import custom.label.lists
import custom.label.maps
import custom.label.metadata
import custom.label.namespaced_maps
import custom.label.nils
import custom.label.numbers
import custom.label.old_metadata
import custom.label.quote_forms
import custom.label.read_cond_splicings
import custom.label.read_conds
import custom.label.regex
import custom.label.sets
import custom.label.strings
import custom.label.symbolic_values
import custom.label.symbols
import custom.label.syntax_quote_forms
import custom.label.tagged_literals
import custom.label.unquote_forms
import custom.label.unquote_splicing_forms
import custom.label.var_quote_forms
import custom.label.vectors
import custom.label.whitespace
