import verify.anon_funcs
import verify.auto_res_markers
import verify.booleans
import verify.characters
import verify.comments
import verify.deref_forms
import verify.discard_exprs
import verify.eval_forms
import verify.keywords
import verify.lists
import verify.maps
import verify.metadata_atom
import verify.metadata_coll
import verify.namespaced_maps
import verify.nils
import verify.numbers
import verify.quote_forms
import verify.read_cond_splicings
import verify.read_conds
import verify.regex
import verify.sets
import verify.strings
import verify.symbolic_values
import verify.symbols
import verify.syntax_quote_forms
import verify.tagged_literals
import verify.unquote_forms
import verify.unquote_splicing_forms
import verify.var_quote_forms
import verify.vectors
import verify.whitespace
