import custom.verify.anon_funcs
import custom.verify.auto_res_markers
import custom.verify.booleans
import custom.verify.characters
import custom.verify.comments
import custom.verify.deref_forms
import custom.verify.discard_exprs
import custom.verify.eval_forms
import custom.verify.keywords
import custom.verify.lists
import custom.verify.maps
import custom.verify.metadata_atom
import custom.verify.metadata_coll
import custom.verify.namespaced_maps
import custom.verify.nils
import custom.verify.numbers
import custom.verify.quote_forms
import custom.verify.read_cond_splicings
import custom.verify.read_conds
import custom.verify.regex
import custom.verify.sets
import custom.verify.strings
import custom.verify.symbolic_values
import custom.verify.symbols
import custom.verify.syntax_quote_forms
import custom.verify.tagged_literals
import custom.verify.unquote_forms
import custom.verify.unquote_splicing_forms
import custom.verify.var_quote_forms
import custom.verify.vectors
import custom.verify.whitespace
